import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './global.css';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { QueryProvider } from '@/query-provider';

const inter = Rubik({
  variable: '--font-inter',
  subsets: ['latin-ext', 'cyrillic-ext'],
});

export const metadata: Metadata = {
  title: {
    default: 'mayorverse',
    template: '%s | mayorverse',
  },
  description: 'Generated by create next app',
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} antialiased bg-gray-800 min-h-dvh min-w-[375px] flex flex-col mx-auto`}
      >
        <QueryProvider>
          <Header />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}

export default RootLayout;
